Post tweet
jcorteza/onboarding-ui pull request #13
Opened 2019-07-02 22:24 UTC by jcorteza

2019-07-03 22:02 UTC, kev-chan requested changes

2019-07-03 22:02 UTC, kev-chan commented on src/view/components/HeaderUI.jsx
> +                        <NavLink exact to="/" activeStyle={{backgroundColor: "#1DA1F2", textDecoration: "underline"}}>Home Timeline</NavLink>
is there way to do this without inline styles?

2019-07-03 22:02 UTC, kev-chan commented on src/view/components/PostTweetUI.jsx
> +        this.refs.postTweetButton.setAttribute("disabled", true);
does this need to be done here?

2019-07-03 22:02 UTC, kev-chan commented on src/view/style/sass/main.scss
> +                margin: 20px 0 20px;
you can shorthand this a bit more

2019-07-03 22:02 UTC, kev-chan commented on src/view/style/sass/main.scss
> +                a {
don't use tags unless you absolutely need to

2019-07-03 22:04 UTC, kev-chan commented
- have coloring on the success/failure message
- don't allow resize of text area

2019-07-08 15:15 UTC, jcorteza commented on src/view/components/PostTweetUI.jsx
> +        this.refs.postTweetButton.setAttribute("disabled", true);
I'm not sure where else I could do this

2019-07-08 23:01 UTC, merged